version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - my-network

  app:
    build: .
    container_name: app
    ports:
      - "5050:5050"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis-container:6379
      - REDIS_EXPIRATION=300
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network

volumes:
  redis-data:

networks:
  my-network:
