global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-app:5050']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
