name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Build the Docker image
      run: docker build ./p2/api --file ./p2/api/Dockerfile --tag danialcoding007/learn-english:latest

    - name: Push the Docker image
      run: docker push danialcoding007/learn-english:latest
